apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podinfo

generatorOptions:
  labels:
    app: podinfo
  disableNameSuffixHash: true


resources:
  - podinfo.yaml
  - namespace.yaml
  - source-podinfo-helm-repository.yaml