---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo-service
  namespace: podinfo
spec:
  chart:
    spec:
      chart: podinfo
      version: '6.5.2'
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
  values:
    ui:
      color: "#cd5b1c"
      message: "Hello, I am podinfo version latest-20250621130825. Hi Tanisa, Good evening."
    service:
      type: NodePort
      nodePort: 32570        
      port: 9898              
      targetPort: 9898        
  install:
    createNamespace: true
  uninstall:
    keepHistory: false
  interval: 10m
