---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sources-helm-repository-podinfo
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./sources/helm-repository
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system